/* ─────────────────────────────────────────────────────────────
   Diccionario ES/EN de todo el copy de marketing.
   Los mockups de producto (escalerilla, dashboards, watch)
   permanecen en español: son la app real.
   ───────────────────────────────────────────────────────────── */

export const STRINGS = {
  es: {
    header: {
      links: [
        ["#como-funciona", "Cómo funciona"],
        ["#el-partido", "El partido"],
        ["#truerank", "TrueRank"],
        ["#precios", "Precios"],
        ["#clubes", "Clubes"],
      ],
      login: "Ingresar",
      download: "Descargar gratis",
    },
    badges: {
      appTop: "Consíguela en el",
      appName: "App Store",
      playTop: "Pronto en",
      playName: "Google Play",
      appAria: "Descargar MatchPro en el App Store",
      qr1: "Escanea con tu teléfono y",
      qr2: "empieza gratis",
    },
    hero: {
      eyebrow: "Tenis · Pádel · Squash · Pickleball",
      t1: "Convierte cada partido en",
      hi: "competencia real",
      sub: "Rivales a tu nivel, escalerillas que se actualizan solas y estadísticas automáticas de cada partido. Sin planillas, sin discusiones de nivel, sin WhatsApp.",
      micro: "Gratis para empezar · Entra con Apple o Google · Sin tarjeta",
      chipUp: "+2 esta semana",
      chipChallenge: "Desafío aceptado · sáb 18:00",
      weatherIdeal: "Ideal para jugar",
      weather: ["Despejado", "Parcial", "Neblina", "Lluvia", "Nieve", "Chubascos", "Tormenta"],
      phoneAlt: "MatchPro: tu próximo partido, matchmaking y escalerillas",
    },
    ticker: [
      ["M. Herrera venció a J. Rivas", "6-4 · 3-6 · 7-6"],
      ["Escalerilla Arica", "325 integrantes"],
      ["C. Vega subió 3 posiciones", "Pádel · Club Cordillera"],
      ["Nuevo desafío aceptado", "D. Soto vs A. Espinoza"],
      ["Torneo Mexicano", "Inscripciones abiertas"],
      ["T. Cáceres defendió el #12", "Squash · Liga interna"],
      ["96% de match", "D. Rojas · Intermedio · a 2,4 km"],
    ],
    stats: [
      ["partidos registrados", 14000, "+"],
      ["jugadores compitiendo", 2800, "+"],
      ["deportes de raqueta", 4, ""],
    ],
    problema: {
      eyebrow: "El problema",
      title: "Si tu competencia funciona así, es difícil mejorar.",
      sub: "La competencia amateur corre sobre planillas, memoria y buena voluntad. Y se nota.",
      ghost: "¿Juegan o no juegan?",
      pains: [
        {
          icon: "chat",
          title: "El grupo de WhatsApp decide quién juega",
          body: "Organizar un partido son 40 mensajes, dos arrepentidos y una hora que nadie confirma.",
        },
        {
          icon: "level",
          title: "Niveles inventados",
          body: "“Intermedio-alto” significa cualquier cosa. Terminas en partidos aburridos o imposibles.",
        },
        {
          icon: "ghost",
          title: "Resultados que se pierden",
          body: "Ganaste 7-6 en el tercero y no quedó registro en ninguna parte. Como si no hubiera pasado.",
        },
        {
          icon: "repeat",
          title: "Siempre los mismos rivales",
          body: "Tu círculo se agotó. Mejorar exige gente nueva de tu nivel, y no sabes dónde está.",
        },
      ],
      punch1: "Tu partido de los martes merece más que una planilla.",
      punch2: "MatchPro lo arregla.",
    },
    como: {
      eyebrow: "Cómo funciona",
      title: "Del teléfono a la cancha en tres pasos.",
      sub: "Tus primeros partidos competitivos son gratis. El resto de tu perfil se completa jugando, no llenando formularios.",
      step: "PASO",
      steps: [
        {
          icon: "download",
          title: "Descarga y entra en un toque",
          body: "Con Apple o Google. Sin formularios eternos, sin tarjeta, sin pagar por mirar.",
        },
        {
          icon: "swords",
          title: "Únete a una escalerilla o desafía",
          body: "Encuentra rivales a tu nivel cerca de ti, o crea una escalerilla privada con tus amigos.",
        },
        {
          icon: "bolt",
          title: "Juega. El resto es automático",
          body: "El resultado actualiza tu ranking, tus estadísticas y tu historial. Tú solo juega.",
        },
      ],
    },
    partido: {
      eyebrow: "El partido completo",
      title: "Un partido de martes, con producción de profesional.",
      sub: "Esto es lo que nadie más hace: el partido entero — antes, durante y después — dentro de un mismo sistema.",
      watchLive: "Partido en vivo · en la muñeca",
      beats: [
        {
          tag: "Durante · ScoreMatch",
          title: "Marca cada punto desde tu muñeca.",
          body: "Con ScoreMatch en tu Apple Watch, tocas tu lado de la pantalla y suma. Cada punto, game y victoria tiene su propia vibración: lo sientes, no lo miras.",
          note: "Opcional — también puedes registrar solo el resultado al terminar.",
          chip: "Punto para ti",
        },
        {
          tag: "Después · MatchPro",
          title: "El resultado sube solo, con estadísticas de verdad.",
          body: "Duración, games, resumen del marcador, rendimiento al saque. Cada partido queda en tu historial y se compara contra tu propio nivel.",
          chip: "1er saque dentro",
          chipStat: "68%",
          alt: "Estadísticas del partido en MatchPro",
        },
        {
          tag: "Siempre · Tu escalerilla",
          title: "La escalerilla se reordena y tu perfil crece.",
          body: "Subes posiciones, tu racha se actualiza y tus próximos desafíos aparecen solos. Y si tu club usa MatchPro, tu nombre queda en la pantalla del lobby con MatchPro TV.",
          chip: "Subiste al #22",
          alt: "Escalerilla en MatchPro",
        },
      ],
    },
    progreso: {
      eyebrow: "Progreso",
      t1: "De profesional amateur a",
      hi: "amateur profesional",
      sub: "Cada partido deja datos. Los datos se vuelven patrones. Los patrones te dicen cómo mejorar. Tu evolución completa, trackeada sola — como un profesional, sin el staff.",
      bullets: [
        {
          title: "Evolución de victorias y de juego",
          body: "Tu momento actual contra tu media histórica. Sabes si estás en alza — con datos, no con sensaciones.",
        },
        {
          title: "Benchmark contra tu nivel",
          body: "Te comparas con el promedio de jugadores de tu nivel: verde si lo superas, rojo si no.",
        },
        {
          title: "Patrones para el próximo partido",
          body: "Dónde ganas, dónde pierdes, qué se repite. La tarea viene hecha: tú solo entra a la cancha.",
        },
      ],
      evoLabel: "Evolución de victorias",
      evoCaption: "Tu win rate subió 13 pts en 8 semanas",
      badgeUp: "En alza",
      badgeRest: "supera tu promedio",
      alt: "Sección Progreso de MatchPro",
    },
    truerank: {
      eyebrow: "TrueRank",
      t1: "Tu nivel no es lo que dices.",
      t2: "Es lo que juegas.",
      sub: "No te preguntamos tu nivel: lo calculamos. TrueRank mejora con cada partido registrado en MatchPro — y es la razón de que tus rivales sean de verdad de tu nivel.",
      provisional: "Sin validar",
      validated: "✓ Validado con partidos",
      rankBody: "Partes con un quiz provisional. Tus primeros partidos lo convierten en tu nivel real.",
      axes: ["Saque", "Resto", "Volea", "Presión", "Consistencia", "Físico"],
      radarCaption: "Radar de tu juego · se construye con tus partidos",
      radarAria: "Radar de atributos de juego calculado por TrueRank",
      hoyTag: "Hoy, en tu perfil",
      hoy: [
        "Ordena tu escalerilla con resultados reales",
        "Tu nivel inicial es provisional — un quiz corto, marcado como “sin validar”",
        "Cada partido jugado afina y valida tu nivel real",
      ],
      prontoTag: "En el roadmap",
      pronto: [
        "Calibración entre clubes y ciudades",
        "Matchmaking inteligente entre deportes",
        "Proyección de progreso por atributo",
      ],
      honesty: "Lo decimos tal cual: TrueRank está en construcción, y se construye con tus partidos.",
    },
    deportes: {
      eyebrow: "Deportes",
      title: "Un sistema para todos los deportes de raqueta.",
      sub: "Mismo perfil, mismo TrueRank, reglas adaptadas a cada deporte.",
      sports: [
        ["Tenis", "Singles y dobles, con reglas reales: tiebreaks, formatos, retiro y W.O."],
        ["Pádel", "Escalerillas de parejas y desafíos por club."],
        ["Squash", "Rankings por caja y ligas internas."],
        ["Pickleball", "La comunidad que más rápido crece."],
      ],
    },
    clubes: {
      eyebrow: "Para tu club",
      title: "MatchPro también impulsa a los clubes.",
      sub: "Los clubes con MatchPro te dan reservas, torneos y tu ranking en la pantalla del lobby — y pueden patrocinar tus competencias.",
      cmTitle: "Digitaliza tu club.",
      cmSub: "Club Manager, la operación del club centralizada.",
      cmBullets: [
        "Reservas con pago integrado",
        "Torneos y escalerillas profesionales",
        "Socios, membresías y facturación automática",
        "Información en tiempo real",
      ],
      cmCta: "Conocer Club Manager →",
      cmDemo: "Agendar una demo",
      tvTitle: "La gestión también se ve.",
      tvSub: "MatchPro TV, incluido gratis con Club Manager.",
      tvBullets: [
        "Canchas, brackets y rankings al segundo",
        "En el lobby, el bar o la TV de tu casa",
        "Activación en 2 minutos con un código",
        "Espacio para sponsors del club",
      ],
      tvCta: "Conocer MatchPro TV →",
      trust: ["✓ Certificado por Transbank", "✓ Infraestructura segura", "✓ Hecho en Chile"],
    },
    pricing: {
      eyebrow: "Precios",
      title: "Jugar es gratis. Competir en serio, cuando quieras.",
      sub: "Tus primeros 2 partidos competitivos son gratis — el paywall llega después del valor, no antes.",
      monthly: "Mensual",
      annual: "Anual · −20%",
      freeName: "Gratis",
      forever: "para siempre",
      freeItems: [
        "Perfil y carta de jugador",
        "Amistosos con amigos ilimitados",
        "Estadísticas básicas del marcador",
        "Ver rankings y escalerillas",
      ],
      freeCta: "Descargar gratis",
      compName: "Competitivo",
      badge: "Recomendado",
      perMonth: "CLP al mes",
      perYear: "CLP al año",
      equivAnnual: "Equivale a $8.325 al mes",
      equivMonthly: "o $99.900 al año (−20%)",
      everything: "Todo lo del plan Gratis",
      compItems: [
        "Matchmaking por nivel y ubicación",
        "Escalerillas, ligas y torneos",
        "Estadísticas avanzadas con ScoreMatch",
        "TrueRank validado y recomendaciones",
      ],
      compCta: "Probar 2 partidos gratis",
      clubBold: "¿Tu club usa MatchPro?",
      clubRest: "Las escalerillas y torneos que tu club patrocina no te cuestan: los cubre el club.",
      notes: ["Cobro seguro vía Transbank", "Cancela cuando quieras", "Sin tarjeta para empezar"],
    },
    testimonios: {
      eyebrow: "Jugadores",
      title: "A gente como tú ya le funciona.",
      quotes: [
        {
          q: "Antes jugaba con los mismos tres amigos. En un mes desafié a diez personas de mi nivel que no conocía.",
          name: "Joaquín R.",
          meta: "Tenis · Escalerilla Arica",
          stat: "▲ 9 posiciones",
        },
        {
          q: "Lo que me convenció fue ver mis estadísticas de saque después de cada partido, sin anotar nada.",
          name: "Daniela S.",
          meta: "Pádel · Club Cordillera",
          stat: "68% 1er saque",
        },
        {
          q: "La escalerilla del club dejó de ser una planilla que nadie actualizaba. Ahora se pelea cada posición.",
          name: "Cristóbal V.",
          meta: "Squash · Liga interna",
          stat: "12 desafíos / mes",
        },
      ],
    },
    faq: {
      eyebrow: "Preguntas frecuentes",
      title: "Lo que preguntan antes de entrar.",
      items: [
        {
          q: "¿Qué es una escalerilla?",
          a: "Un ranking vivo entre un grupo de jugadores: desafías a quienes están sobre ti, y si ganas, subes. Puede ser pública (tu ciudad, tu club) o privada (tus amigos). Se actualiza sola con cada resultado.",
        },
        {
          q: "¿Cuánto cuesta empezar?",
          a: "Nada. Entras con Apple o Google, sin tarjeta. Jugar amistosos con amigos es gratis para siempre, y tus primeros 2 partidos competitivos también. El plan Competitivo ($9.990 CLP/mes) desbloquea matchmaking, escalerillas, ligas y estadísticas avanzadas.",
        },
        {
          q: "¿Cómo sabe MatchPro cuál es mi nivel?",
          a: "No te lo preguntamos: lo calculamos. Partes con una autoevaluación corta marcada como provisional, y TrueRank la valida con tus primeros partidos reales. Tu nivel deja de ser una opinión.",
        },
        {
          q: "¿Necesito un Apple Watch?",
          a: "No. ScoreMatch (marcar punto a punto desde el reloj) es opcional y suma estadísticas más finas. Sin reloj, registras el resultado al terminar y listo.",
        },
        {
          q: "¿Y si mi club ya usa MatchPro?",
          a: "Mejor: las escalerillas y torneos que patrocina tu club no te cuestan, reservas cancha desde la app y tu ranking aparece en las pantallas del club con MatchPro TV.",
        },
        {
          q: "¿Qué deportes están soportados?",
          a: "Tenis, pádel, squash y pickleball — con reglas y formatos propios de cada uno.",
        },
      ],
    },
    cta: {
      t1: "La competencia amateur está",
      hi: "cambiando.",
      sub: "Tu próximo partido puede quedar en la historia — la tuya. Empieza gratis, sin tarjeta, en menos de un minuto.",
    },
    footer: {
      tagline:
        "Convierte cada partido en competencia real. Tenis, pádel, squash y pickleball — hecho en Chile.",
      cols: [
        {
          title: "Producto",
          links: [
            ["#como-funciona", "Cómo funciona"],
            ["#el-partido", "El partido completo"],
            ["#truerank", "TrueRank"],
            ["#precios", "Precios"],
            ["https://getmatchpro.com/login", "Ingresar a la web"],
          ],
        },
        {
          title: "Ecosistema",
          links: [
            ["https://scorematch.app", "ScoreMatch"],
            ["https://getmatchpro.com/club-management", "Club Manager"],
            ["https://matchpro.tv", "MatchPro TV"],
          ],
        },
        {
          title: "Legal",
          links: [
            ["https://getmatchpro.com/terminos", "Términos de servicio"],
            ["https://getmatchpro.com/privacidad", "Política de privacidad"],
          ],
        },
      ],
      bottom: "© 2026 MatchPro SpA · Partner certificado Transbank",
      motto: "Juego, set, MatchPro.",
    },
  },

  en: {
    header: {
      links: [
        ["#como-funciona", "How it works"],
        ["#el-partido", "The match"],
        ["#truerank", "TrueRank"],
        ["#precios", "Pricing"],
        ["#clubes", "Clubs"],
      ],
      login: "Sign in",
      download: "Download free",
    },
    badges: {
      appTop: "Download on the",
      appName: "App Store",
      playTop: "Coming soon to",
      playName: "Google Play",
      appAria: "Download MatchPro on the App Store",
      qr1: "Scan with your phone and",
      qr2: "start free",
    },
    hero: {
      eyebrow: "Tennis · Padel · Squash · Pickleball",
      t1: "Turn every match into",
      hi: "real competition",
      sub: "Rivals at your level, ladders that update themselves and automatic stats for every match. No spreadsheets, no level debates, no WhatsApp.",
      micro: "Free to start · Sign in with Apple or Google · No card",
      chipUp: "+2 this week",
      chipChallenge: "Challenge accepted · Sat 6 pm",
      weatherIdeal: "Perfect for playing",
      weather: ["Clear", "Partly cloudy", "Fog", "Rain", "Snow", "Showers", "Storm"],
      phoneAlt: "MatchPro: your next match, matchmaking and ladders",
    },
    ticker: [
      ["M. Herrera beat J. Rivas", "6-4 · 3-6 · 7-6"],
      ["Arica Ladder", "325 members"],
      ["C. Vega climbed 3 spots", "Padel · Club Cordillera"],
      ["New challenge accepted", "D. Soto vs A. Espinoza"],
      ["Mexicano Tournament", "Registration open"],
      ["T. Cáceres defended #12", "Squash · Internal league"],
      ["96% match", "D. Rojas · Intermediate · 2.4 km away"],
    ],
    stats: [
      ["matches recorded", 14000, "+"],
      ["players competing", 2800, "+"],
      ["racket sports", 4, ""],
    ],
    problema: {
      eyebrow: "The problem",
      title: "If your competition works like this, improving is hard.",
      sub: "Amateur competition runs on spreadsheets, memory and goodwill. And it shows.",
      ghost: "Are we playing or not?",
      pains: [
        {
          icon: "chat",
          title: "The WhatsApp group decides who plays",
          body: "Setting up one match takes 40 messages, two dropouts and a time slot nobody confirms.",
        },
        {
          icon: "level",
          title: "Made-up skill levels",
          body: "“Upper-intermediate” can mean anything. You end up in boring or impossible matches.",
        },
        {
          icon: "ghost",
          title: "Results that vanish",
          body: "You won 7-6 in the third and there's no record anywhere. As if it never happened.",
        },
        {
          icon: "repeat",
          title: "Always the same rivals",
          body: "Your circle ran dry. Improving takes new people at your level — and you don't know where they are.",
        },
      ],
      punch1: "Your Tuesday match deserves more than a spreadsheet.",
      punch2: "MatchPro fixes it.",
    },
    como: {
      eyebrow: "How it works",
      title: "From your phone to the court in three steps.",
      sub: "Your first competitive matches are free. The rest of your profile gets completed by playing, not by filling out forms.",
      step: "STEP",
      steps: [
        {
          icon: "download",
          title: "Download and sign in with one tap",
          body: "With Apple or Google. No endless forms, no card, no paying just to look around.",
        },
        {
          icon: "swords",
          title: "Join a ladder or challenge someone",
          body: "Find rivals at your level near you, or create a private ladder with your friends.",
        },
        {
          icon: "bolt",
          title: "Play. The rest is automatic",
          body: "The result updates your ranking, your stats and your history. You just play.",
        },
      ],
    },
    partido: {
      eyebrow: "The complete match",
      title: "A Tuesday match, with professional production.",
      sub: "This is what nobody else does: the entire match — before, during and after — inside one system.",
      watchLive: "Live match · on your wrist",
      beats: [
        {
          tag: "During · ScoreMatch",
          title: "Score every point from your wrist.",
          body: "With ScoreMatch on your Apple Watch, you tap your side of the screen and it counts. Every point, game and win has its own haptic: you feel it, you don't stare at it.",
          note: "Optional — you can also just log the final score when you're done.",
          chip: "Point for you",
        },
        {
          tag: "After · MatchPro",
          title: "The result uploads itself, with real stats.",
          body: "Duration, games, score summary, serve performance. Every match goes into your history and gets compared against your own level.",
          chip: "1st serve in",
          chipStat: "68%",
          alt: "Match statistics in MatchPro",
        },
        {
          tag: "Always · Your ladder",
          title: "The ladder reorders and your profile grows.",
          body: "You climb spots, your streak updates and your next challenges appear on their own. And if your club uses MatchPro, your name shows up on the lobby screen with MatchPro TV.",
          chip: "You climbed to #22",
          alt: "Ladder in MatchPro",
        },
      ],
    },
    progreso: {
      eyebrow: "Progress",
      t1: "From amateur professional to",
      hi: "professional amateur",
      sub: "Every match leaves data. Data becomes patterns. Patterns tell you how to improve. Your whole evolution, tracked on its own — like a pro, without the staff.",
      bullets: [
        {
          title: "Win and game evolution",
          body: "Your current form against your historical average. You know if you're on the rise — with data, not feelings.",
        },
        {
          title: "Benchmark against your level",
          body: "You're compared with the average player at your level: green if you beat it, red if you don't.",
        },
        {
          title: "Patterns for your next match",
          body: "Where you win, where you lose, what keeps repeating. Homework's done — you just step on court.",
        },
      ],
      evoLabel: "Win evolution",
      evoCaption: "Your win rate climbed 13 pts in 8 weeks",
      badgeUp: "On the rise",
      badgeRest: "above your average",
      alt: "Progress section in MatchPro",
    },
    truerank: {
      eyebrow: "TrueRank",
      t1: "Your level isn't what you say.",
      t2: "It's what you play.",
      sub: "We don't ask your level: we calculate it. TrueRank improves with every match recorded in MatchPro — and it's the reason your rivals are truly at your level.",
      provisional: "Unvalidated",
      validated: "✓ Validated with matches",
      rankBody: "You start with a provisional quiz. Your first matches turn it into your real level.",
      axes: ["Serve", "Return", "Volley", "Pressure", "Consistency", "Fitness"],
      radarCaption: "Your game radar · built with your matches",
      radarAria: "Game attribute radar calculated by TrueRank",
      hoyTag: "Today, in your profile",
      hoy: [
        "Orders your ladder with real results",
        "Your starting level is provisional — a short quiz, marked “unvalidated”",
        "Every match you play refines and validates your real level",
      ],
      prontoTag: "On the roadmap",
      pronto: [
        "Calibration across clubs and cities",
        "Smart matchmaking across sports",
        "Progress projection by attribute",
      ],
      honesty: "We'll say it straight: TrueRank is under construction, and it's built with your matches.",
    },
    deportes: {
      eyebrow: "Sports",
      title: "One system for every racket sport.",
      sub: "Same profile, same TrueRank, rules adapted to each sport.",
      sports: [
        ["Tennis", "Singles and doubles, with real rules: tiebreaks, formats, retirement and W.O."],
        ["Padel", "Doubles ladders and club challenges."],
        ["Squash", "Box rankings and internal leagues."],
        ["Pickleball", "The fastest-growing community."],
      ],
    },
    clubes: {
      eyebrow: "For your club",
      title: "MatchPro powers clubs too.",
      sub: "Clubs on MatchPro give you bookings, tournaments and your ranking on the lobby screen — and they can sponsor your competitions.",
      cmTitle: "Digitize your club.",
      cmSub: "Club Manager, the club's operation centralized.",
      cmBullets: [
        "Bookings with integrated payments",
        "Professional tournaments and ladders",
        "Members, memberships and automatic billing",
        "Real-time information",
      ],
      cmCta: "Discover Club Manager →",
      cmDemo: "Book a demo",
      tvTitle: "Management you can see.",
      tvSub: "MatchPro TV, included free with Club Manager.",
      tvBullets: [
        "Courts, brackets and rankings up to the second",
        "In the lobby, the bar or your living room TV",
        "Activated in 2 minutes with a code",
        "Space for club sponsors",
      ],
      tvCta: "Discover MatchPro TV →",
      trust: ["✓ Certified by Transbank", "✓ Secure infrastructure", "✓ Made in Chile"],
    },
    pricing: {
      eyebrow: "Pricing",
      title: "Playing is free. Compete seriously whenever you want.",
      sub: "Your first 2 competitive matches are free — the paywall comes after the value, not before.",
      monthly: "Monthly",
      annual: "Annual · −20%",
      freeName: "Free",
      forever: "forever",
      freeItems: [
        "Profile and player card",
        "Unlimited friendlies with friends",
        "Basic scoreboard stats",
        "View rankings and ladders",
      ],
      freeCta: "Download free",
      compName: "Competitive",
      badge: "Recommended",
      perMonth: "CLP / month",
      perYear: "CLP / year",
      equivAnnual: "That's $8,325 a month",
      equivMonthly: "or $99,900 a year (−20%)",
      everything: "Everything in Free",
      compItems: [
        "Matchmaking by level and location",
        "Ladders, leagues and tournaments",
        "Advanced stats with ScoreMatch",
        "Validated TrueRank and recommendations",
      ],
      compCta: "Try 2 matches free",
      clubBold: "Does your club use MatchPro?",
      clubRest: "Ladders and tournaments sponsored by your club cost you nothing: the club covers them.",
      notes: ["Secure payments via Transbank", "Cancel anytime", "No card to start"],
    },
    testimonios: {
      eyebrow: "Players",
      title: "It's already working for people like you.",
      quotes: [
        {
          q: "I used to play with the same three friends. In a month I challenged ten people at my level I'd never met.",
          name: "Joaquín R.",
          meta: "Tennis · Arica Ladder",
          stat: "▲ 9 spots",
        },
        {
          q: "What sold me was seeing my serve stats after every match, without writing anything down.",
          name: "Daniela S.",
          meta: "Padel · Club Cordillera",
          stat: "68% 1st serve",
        },
        {
          q: "The club ladder stopped being a spreadsheet nobody updated. Now every spot is fought for.",
          name: "Cristóbal V.",
          meta: "Squash · Internal league",
          stat: "12 challenges / mo",
        },
      ],
    },
    faq: {
      eyebrow: "FAQ",
      title: "What people ask before joining.",
      items: [
        {
          q: "What is a ladder?",
          a: "A living ranking among a group of players: you challenge those above you, and if you win, you climb. It can be public (your city, your club) or private (your friends). It updates itself with every result.",
        },
        {
          q: "How much does it cost to start?",
          a: "Nothing. You sign in with Apple or Google, no card. Friendlies with friends are free forever, and so are your first 2 competitive matches. The Competitive plan ($9,990 CLP/mo) unlocks matchmaking, ladders, leagues and advanced stats.",
        },
        {
          q: "How does MatchPro know my level?",
          a: "We don't ask — we calculate it. You start with a short self-assessment marked as provisional, and TrueRank validates it with your first real matches. Your level stops being an opinion.",
        },
        {
          q: "Do I need an Apple Watch?",
          a: "No. ScoreMatch (scoring point by point from the watch) is optional and adds finer stats. Without a watch, you log the result when you finish and that's it.",
        },
        {
          q: "What if my club already uses MatchPro?",
          a: "Even better: ladders and tournaments sponsored by your club cost you nothing, you book courts from the app, and your ranking shows up on the club screens with MatchPro TV.",
        },
        {
          q: "Which sports are supported?",
          a: "Tennis, padel, squash and pickleball — each with its own rules and formats.",
        },
      ],
    },
    cta: {
      t1: "Amateur competition is",
      hi: "changing.",
      sub: "Your next match can go down in history — yours. Start free, no card, in under a minute.",
    },
    footer: {
      tagline:
        "Turn every match into real competition. Tennis, padel, squash and pickleball — made in Chile.",
      cols: [
        {
          title: "Product",
          links: [
            ["#como-funciona", "How it works"],
            ["#el-partido", "The complete match"],
            ["#truerank", "TrueRank"],
            ["#precios", "Pricing"],
            ["https://getmatchpro.com/login", "Sign in to the web"],
          ],
        },
        {
          title: "Ecosystem",
          links: [
            ["https://scorematch.app", "ScoreMatch"],
            ["https://getmatchpro.com/club-management", "Club Manager"],
            ["https://matchpro.tv", "MatchPro TV"],
          ],
        },
        {
          title: "Legal",
          links: [
            ["https://getmatchpro.com/terminos", "Terms of Service"],
            ["https://getmatchpro.com/privacidad", "Privacy Policy"],
          ],
        },
      ],
      bottom: "© 2026 MatchPro SpA · Certified Transbank partner",
      motto: "Game, set, MatchPro.",
    },
  },
};
