/* ─────────────────────────────────────────────────────────────
   Diccionario ES/EN — SOLO copy de marketing.
   Los mocks del producto (panel, TV, watch) permanecen en
   español: son réplicas del producto real, que hoy opera en ES.
   Los títulos con acento se guardan como [antes, acento, después]
   y se renderizan con <AccentTitle/>.
   ───────────────────────────────────────────────────────────── */

export const STRINGS = {
  es: {
    header: {
      links: [
        ["#producto", "Producto"],
        ["#ecosistema", "Ecosistema"],
        ["#clientes", "Clientes"],
        ["#faq", "Preguntas"],
      ],
      demo: "Agendar demo",
      demoSticky: "Agendar demo · 30 min",
      menuAria: "Abrir menú",
    },
    cta: { demo: "Agendar demo", whatsapp: "WhatsApp" },
    hero: {
      eyebrow: "Software de gestión · Clubes de raqueta",
      h1a: "El siguiente nivel de tu club no es deportivo. ",
      h1b: "Es operativo.",
      sub: "Reservas, pagos, socios, torneos y ranking en una sola plataforma. Sin planillas. Sin desorden. Sin trabajo manual.",
      micro: "MatchPro TV incluido · Pagos con Transbank · Plan todo incluido",
      vistas: ["Dashboard", "Calendario", "Cuadro del torneo"],
      unPanel: "un solo panel",
      badge: "Nueva reserva confirmada — pago recibido",
      vistasAria: "Vistas del panel",
    },
    ticker: [
      "P. Fuentealba venció a D. Aravena · Escalerilla General",
      "Cancha 2 reservada · 18:00 · pago Webpay recibido",
      "Mexicano Semanal · 6/9 partidos · en la TV del club",
      "Nuevo socio: F. Astudillo · vía código QR",
      "Desafío aceptado: C. Riffo vs A. Baeza · sáb 10:00",
      "Reporte mensual listo · ingresos +12%",
    ],
    clientes: {
      eyebrow: "Clubes que ya operan con MatchPro",
      stat1: "partidos registrados",
      stat2: "canchas gestionadas",
    },
    problema: {
      eyebrow: "El problema",
      title: ["Si tu club funciona así, ", "estás perdiendo dinero", "."],
      sub: "No es falta de trabajo. Es falta de sistema.",
      dolores: [
        ["📋", "Reservas en planillas", "Dobles reservas, canchas vacías que nadie ve y horas muertas que nadie cobra."],
        ["💸", "Caja sin trazabilidad", "Pagos en efectivo, transferencias sueltas y fin de mes cuadrando a mano."],
        ["🏆", "Torneos a pulso", "Brackets en pizarra, resultados en papel y horas de trabajo por campeonato."],
        ["👥", "Socios sin historial", "Nadie sabe quién juega, cuánto paga ni cuándo dejó de venir — hasta que se fue."],
        ["💬", "WhatsApp como sistema", "Reservas, cobros y reclamos mezclados en un chat que nadie puede auditar."],
      ],
      pill: "La informalidad operativa siempre termina afectando los resultados.",
    },
    video: {
      eyebrow: "Cómo funciona",
      title: ["Mira Club Manager ", "por dentro", "."],
      sub: "El salto tecnológico para la gestión de tu club, explicado en un video.",
      playAria: "Reproducir: Club Manager, el salto tecnológico para la gestión de tu club",
      sent: "Listo. Te llegará la demo grabada a",
      placeholder: "¿Sin tiempo ahora? Te enviamos la demo grabada",
      enviar: "Enviar",
      emailLabel: "Correo electrónico",
    },
    operacion: {
      eyebrow: "Operación",
      title: ["Tu operación completa, ", "bajo control", "."],
      sub: "Los flujos donde un club pierde plata — resueltos en un solo panel. Así se ve por dentro, de verdad.",
      pasos: [
        {
          eyebrow: "Reservas",
          t: "Cada hora de cancha, visible y cobrada.",
          d: "Calendario en tiempo real, precios por franja horaria y reservas públicas por link o QR: los externos reservan y pagan sin crear cuenta. Las horas muertas dejan de ser invisibles.",
          pill: "Mayor ocupación, cero dobles reservas.",
        },
        {
          eyebrow: "Pagos",
          t: "La plata entra por un solo lugar.",
          d: "Cobros integrados con Transbank: reservas, cuotas de socios e inscripciones a torneos quedan pagados y registrados en el momento, con estado visible — pagado, pendiente o fallido.",
          pill: "Transparencia total, conciliación automática.",
        },
        {
          eyebrow: "Competencias",
          t: "Torneos y escalerillas en minutos, no en tardes.",
          d: "Un asistente de 7 pasos arma el torneo completo — formato, cupos, puntuación y fixture optimizado para tus canchas. Las escalerillas corren solas con las reglas que definas. Y todo se proyecta en vivo en la TV del club.",
          pill: "De la pizarra al fixture automático.",
        },
        {
          eyebrow: "Pantallas del club",
          t: "Tu operación, en todas las pantallas del club.",
          d: "MatchPro TV convierte cualquier televisor en el dashboard del club: estado de canchas al segundo, ranking, brackets que se redibujan solos, sponsors por tier y reservas por QR. Todo se configura desde el panel — la TV no se toca.",
          pill: "Incluido en todos los planes. Sin costo extra.",
        },
        {
          eyebrow: "Finanzas",
          t: "Decisiones con números, no con intuición.",
          d: "Ingresos por día, semana, mes y año; rendimiento por cancha; tendencia de los últimos 12 meses. Reportes exportables en PDF y CSV que el directorio entiende en una pantalla.",
          pill: "El fin de mes deja de ser arqueología.",
        },
      ],
      tvModos: ["Grid editable", "Rotación automática", "Código de 6 dígitos"],
      tvAria: "Modos de MatchPro TV",
    },
    competencia: {
      eyebrow: "Competencia",
      title: ["Un club que compite ", "es un club que vuelve", "."],
      sub: "La competencia organizada es retención: socios que juegan más, reservan más y se quedan.",
      items: [
        ["Escalerillas y desafíos", "Tus socios se retan entre ellos con reglas que tú defines; el ranking se reordena solo con cada resultado confirmado."],
        ["Torneos sin pizarra", "Eliminatorias, grupos, americanos y mexicanos: el fixture se arma solo, optimizando el uso de tus canchas."],
        ["Ranking que no se discute", "El nivel no se declara: se calcula con TrueRank a partir de los partidos jugados y confirmados por ambos jugadores."],
      ],
      caption1: "Tus socios ya la conocen: es la misma escalerilla de la ",
      caption2: "app MatchPro",
      miniDesafios: "Gestión de Desafíos",
      miniTasa: "tasa de aceptación",
      miniCompletados: "63 completados este mes",
      miniTorneo: "Torneo en curso",
      miniVivo: "● En vivo",
      miniProgreso: "6/9 partidos · en la TV del club",
    },
    caso: {
      eyebrow: "Caso real · placeholder",
      quote:
        '"Antes cerraba el mes con tres planillas y una calculadora. Hoy el directorio ve los números en pantalla y las canchas se arriendan solas."',
      nombre: "Rodrigo Manríquez",
      cargo: "Administrador · Club Los Aromos",
      metrica: "ocupación en 90 días",
    },
    ecosistema: {
      eyebrow: "El ecosistema MatchPro",
      title: ["No compraste un software. ", "Encendiste una liga", "."],
      sub: "Esto es lo que ningún otro sistema de gestión puede darte: sigue el martes por la noche de Martín, socio de tu club.",
      conocer: "Conocer →",
      momentos: [
        {
          producto: "App MatchPro",
          t: "La app le recomienda tu club",
          d: "Martín abre MatchPro buscando cancha. La app le sugiere tus canchas disponibles y reserva, pagado, en dos toques. Tu club aparece donde ya están los jugadores.",
        },
        {
          producto: "ScoreMatch",
          t: "Marca el punto. Siente el partido.",
          d: "Cada punto se marca en el Apple Watch: la cifra llena el reloj y cada punto vibra. Resultados validados punto a punto, no dictados de memoria.",
        },
        {
          producto: "MatchPro TV",
          badge: "Incluido en tu plan",
          t: "Su nombre aparece en la TV del lobby",
          d: "Rankings, canchas y marcadores en vivo en cualquier televisor del club — el lobby se vuelve broadcast. Incluido en todos los planes, sin costo extra.",
        },
        {
          producto: "TrueRank",
          t: "Su ranking se recalcula solo",
          d: "El nivel no se declara: se juega. TrueRank convierte cada resultado en un ranking que nadie puede discutir.",
        },
      ],
      cierre1: "MatchPro TV incluido en todos los planes.",
      cierre2: "ScoreMatch y la app MatchPro, gratis para tus socios.",
    },
    implementacion: {
      eyebrow: "Implementación",
      title: ["Cambiarse ", "no duele", "."],
      sub: "La mayoría de los clubes queda operativo el mismo día de la configuración.",
      pasos: [
        ["Conversamos", "Demo de 30 minutos por videollamada. Vemos tu operación actual y qué necesitas resolver primero."],
        ["Activamos", "Sesión guiada de configuración con nuestro equipo: canchas, tarifas, socios y medios de pago. Migramos tus datos desde planillas."],
        ["Creces", "Tu club opera en la plataforma y tú ves los números. Soporte directo por WhatsApp cuando lo necesites."],
      ],
      ctaLinea: "Demo de 30 minutos · sin compromiso · operativo el mismo día",
    },
    confianza: {
      eyebrow: "Confianza",
      title: ["Un sistema serio para ", "operar en serio", "."],
      sub: "Hecho en Chile, con estándares formales y respaldo real.",
      items: [
        ["Pagos certificados por Transbank", "Cobros bajo estándares internacionales de seguridad para transacciones digitales."],
        ["Implementación acompañada", "No te dejamos solo con un manual: configuramos el sistema contigo, con tus datos reales."],
        ["Soporte que sabe de deporte", "Atención directa de un equipo con experiencia en gestión de clubes de raqueta, no un call center."],
        ["Se adapta a tu operación", "Tarifas, horarios, reglas de reserva y formatos de competencia configurables según tu club."],
      ],
    },
    cierre: {
      eyebrow: "El siguiente paso",
      title: ["Tu club, ", "profesional desde el primer mes", "."],
      sub: "Demo de 30 minutos · Implementación acompañada · Sin permanencia",
      faqTitle: "Preguntas frecuentes",
      faqs: [
        [
          "¿Cuánto tarda la implementación?",
          "La configuración inicial se hace en una sesión guiada con nuestro equipo y la mayoría de los clubes queda operativo el mismo día. La migración de datos históricos desde planillas toma hasta una semana, según el volumen.",
        ],
        [
          "¿Qué pasa con mis datos actuales?",
          "Los migramos nosotros: socios, tarifas y reservas vigentes se cargan desde tus planillas durante la implementación. No partes de cero.",
        ],
        [
          "¿Mis socios tienen que pagar algo?",
          "No. La app MatchPro es gratuita para tus socios, y ScoreMatch también. El club paga la plataforma; los jugadores solo la usan.",
        ],
        [
          "¿Cómo se cobra Club Manager?",
          "Plan todo incluido: un fee base mensual por club que incluye todas las funcionalidades y un cupo de jugadores, más cargos según uso (jugadores adicionales y comisión por transacción en torneos). MatchPro TV va incluido. En la demo te damos el valor exacto para tu club.",
        ],
        [
          "¿Qué medios de pago puedo ofrecer?",
          "Pagos en línea integrados vía Transbank (Webpay), además de registro manual para efectivo y transferencias, para que toda la caja quede en un solo lugar.",
        ],
      ],
    },
    footer: {
      desc: "Software de gestión para clubes de raqueta: reservas, pagos, socios, torneos y ranking. Un producto de MatchPro.",
      producto: "Producto",
      productoLinks: [
        ["#producto", "Operación"],
        ["#ecosistema", "Ecosistema"],
        ["#clientes", "Clientes"],
        ["#faq", "Preguntas frecuentes"],
      ],
      ecosistema: "Ecosistema",
      matchproJugadores: "MatchPro — para jugadores",
      contacto: "Contacto",
      agendar: "Agenda una demo",
      copyright: "Hecho en Chile",
      transbank: "Pagos certificados por Transbank",
    },
  },

  en: {
    header: {
      links: [
        ["#producto", "Product"],
        ["#ecosistema", "Ecosystem"],
        ["#clientes", "Clients"],
        ["#faq", "FAQ"],
      ],
      demo: "Book a demo",
      demoSticky: "Book a demo · 30 min",
      menuAria: "Open menu",
    },
    cta: { demo: "Book a demo", whatsapp: "WhatsApp" },
    hero: {
      eyebrow: "Management software · Racquet clubs",
      h1a: "Your club's next level isn't athletic. ",
      h1b: "It's operational.",
      sub: "Bookings, payments, members, tournaments and rankings in one platform. No spreadsheets. No chaos. No manual work.",
      micro: "MatchPro TV included · Transbank payments · All-inclusive plan",
      vistas: ["Dashboard", "Calendar", "Tournament bracket"],
      unPanel: "one single panel",
      badge: "New booking confirmed — payment received",
      vistasAria: "Panel views",
    },
    ticker: [
      "P. Fuentealba beat D. Aravena · General Ladder",
      "Court 2 booked · 6:00 PM · Webpay payment received",
      "Weekly Mexicano · 6/9 matches · on the club TV",
      "New member: F. Astudillo · via QR code",
      "Challenge accepted: C. Riffo vs A. Baeza · Sat 10:00",
      "Monthly report ready · revenue +12%",
    ],
    clientes: {
      eyebrow: "Clubs already running on MatchPro",
      stat1: "matches recorded",
      stat2: "courts managed",
    },
    problema: {
      eyebrow: "The problem",
      title: ["If your club runs like this, ", "you're losing money", "."],
      sub: "It's not a lack of work. It's a lack of system.",
      dolores: [
        ["📋", "Bookings in spreadsheets", "Double bookings, empty courts nobody sees and dead hours nobody charges for."],
        ["💸", "Untraceable cash flow", "Cash payments, loose transfers and month-end closed by hand."],
        ["🏆", "Tournaments by hand", "Whiteboard brackets, paper results and hours of work per championship."],
        ["👥", "Members without history", "Nobody knows who plays, who pays or when they stopped coming — until they're gone."],
        ["💬", "WhatsApp as a system", "Bookings, charges and complaints mixed in a chat nobody can audit."],
      ],
      pill: "Operational informality always ends up hurting the numbers.",
    },
    video: {
      eyebrow: "How it works",
      title: ["See Club Manager ", "from the inside", "."],
      sub: "The technology leap for your club's management, explained in one video.",
      playAria: "Play: Club Manager, the technology leap for your club's management",
      sent: "Done. The recorded demo is on its way to",
      placeholder: "No time now? We'll send you the recorded demo",
      enviar: "Send",
      emailLabel: "Email address",
    },
    operacion: {
      eyebrow: "Operations",
      title: ["Your entire operation, ", "under control", "."],
      sub: "The flows where clubs lose money — solved in a single panel. This is what it actually looks like inside.",
      pasos: [
        {
          eyebrow: "Bookings",
          t: "Every court hour, visible and paid.",
          d: "Real-time calendar, time-slot pricing and public bookings via link or QR: outside players book and pay without creating an account. Dead hours stop being invisible.",
          pill: "Higher occupancy, zero double bookings.",
        },
        {
          eyebrow: "Payments",
          t: "Money comes in through one door.",
          d: "Payments integrated with Transbank: bookings, membership fees and tournament entries are paid and recorded on the spot, with visible status — paid, pending or failed.",
          pill: "Full transparency, automatic reconciliation.",
        },
        {
          eyebrow: "Competitions",
          t: "Tournaments and ladders in minutes, not afternoons.",
          d: "A 7-step wizard builds the whole tournament — format, capacity, scoring and a fixture optimized for your courts. Ladders run themselves with the rules you define. And everything streams live to the club TV.",
          pill: "From whiteboard to automatic fixture.",
        },
        {
          eyebrow: "Club screens",
          t: "Your operation, on every screen in the club.",
          d: "MatchPro TV turns any television into the club's dashboard: court status by the second, rankings, self-updating brackets, tiered sponsors and QR bookings. Everything is configured from the panel — you never touch the TV.",
          pill: "Included in every plan. No extra cost.",
        },
        {
          eyebrow: "Finance",
          t: "Decisions with numbers, not intuition.",
          d: "Revenue by day, week, month and year; performance by court; 12-month trend. Reports exportable to PDF and CSV that your board understands in one screen.",
          pill: "Month-end stops being archaeology.",
        },
      ],
      tvModos: ["Editable grid", "Auto rotation", "6-digit code"],
      tvAria: "MatchPro TV modes",
    },
    competencia: {
      eyebrow: "Competition",
      title: ["A club that competes ", "is a club that comes back", "."],
      sub: "Organized competition is retention: members who play more, book more and stay.",
      items: [
        ["Ladders and challenges", "Your members challenge each other under rules you define; the ranking reorders itself with every confirmed result."],
        ["Tournaments without whiteboards", "Knockouts, groups, americano and mexicano formats: the fixture builds itself, optimizing your courts."],
        ["A ranking nobody argues with", "Skill isn't declared: it's calculated with TrueRank from matches played and confirmed by both players."],
      ],
      caption1: "Your members already know it: it's the same ladder as the ",
      caption2: "MatchPro app",
      miniDesafios: "Challenge Management",
      miniTasa: "acceptance rate",
      miniCompletados: "63 completed this month",
      miniTorneo: "Live tournament",
      miniVivo: "● Live",
      miniProgreso: "6/9 matches · on the club TV",
    },
    caso: {
      eyebrow: "Case study · placeholder",
      quote:
        '"I used to close the month with three spreadsheets and a calculator. Today the board sees the numbers on screen and the courts rent themselves."',
      nombre: "Rodrigo Manríquez",
      cargo: "Administrator · Club Los Aromos",
      metrica: "occupancy in 90 days",
    },
    ecosistema: {
      eyebrow: "The MatchPro ecosystem",
      title: ["You didn't buy software. ", "You switched on a league", "."],
      sub: "This is what no other management system can give you: follow Martín's Tuesday night, a member of your club.",
      conocer: "Learn more →",
      momentos: [
        {
          producto: "MatchPro App",
          t: "The app recommends your club",
          d: "Martín opens MatchPro looking for a court. The app suggests your available courts and he books, paid, in two taps. Your club shows up where the players already are.",
        },
        {
          producto: "ScoreMatch",
          t: "Score the point. Feel the match.",
          d: "Every point is scored on the Apple Watch: the score fills the screen and every point vibrates. Results validated point by point, not dictated from memory.",
        },
        {
          producto: "MatchPro TV",
          badge: "Included in your plan",
          t: "His name shows up on the lobby TV",
          d: "Rankings, courts and live scores on any television in the club — the lobby becomes a broadcast. Included in every plan, at no extra cost.",
        },
        {
          producto: "TrueRank",
          t: "His ranking updates itself",
          d: "Skill isn't declared: it's played. TrueRank turns every result into a ranking nobody can argue with.",
        },
      ],
      cierre1: "MatchPro TV included in every plan.",
      cierre2: "ScoreMatch and the MatchPro app, free for your members.",
    },
    implementacion: {
      eyebrow: "Onboarding",
      title: ["Switching ", "doesn't hurt", "."],
      sub: "Most clubs are up and running the same day they're configured.",
      pasos: [
        ["We talk", "A 30-minute demo over video call. We look at your current operation and what you need to solve first."],
        ["We activate", "A guided setup session with our team: courts, pricing, members and payment methods. We migrate your data from spreadsheets."],
        ["You grow", "Your club runs on the platform and you see the numbers. Direct WhatsApp support whenever you need it."],
      ],
      ctaLinea: "30-minute demo · no commitment · live the same day",
    },
    confianza: {
      eyebrow: "Trust",
      title: ["A serious system for ", "running things seriously", "."],
      sub: "Built in Chile, with formal standards and real backing.",
      items: [
        ["Payments certified by Transbank", "Charges under international security standards for digital transactions."],
        ["Guided onboarding", "We don't leave you alone with a manual: we configure the system with you, using your real data."],
        ["Support that knows the sport", "Direct attention from a team experienced in racquet club management, not a call center."],
        ["Adapts to your operation", "Pricing, schedules, booking rules and competition formats configurable for your club."],
      ],
    },
    cierre: {
      eyebrow: "The next step",
      title: ["Your club, ", "professional from month one", "."],
      sub: "30-minute demo · Guided onboarding · No lock-in",
      faqTitle: "Frequently asked questions",
      faqs: [
        [
          "How long does onboarding take?",
          "Initial setup happens in a guided session with our team, and most clubs are live the same day. Migrating historical data from spreadsheets takes up to a week, depending on volume.",
        ],
        [
          "What happens to my current data?",
          "We migrate it for you: members, pricing and active bookings are loaded from your spreadsheets during onboarding. You don't start from zero.",
        ],
        [
          "Do my members have to pay anything?",
          "No. The MatchPro app is free for your members, and so is ScoreMatch. The club pays for the platform; players just use it.",
        ],
        [
          "How is Club Manager priced?",
          "All-inclusive plan: a monthly base fee per club covering every feature and a player quota, plus usage-based charges (additional players and a per-transaction fee on tournaments). MatchPro TV is included. We'll give you the exact price for your club in the demo.",
        ],
        [
          "Which payment methods can I offer?",
          "Online payments integrated via Transbank (Webpay), plus manual registration for cash and transfers, so your whole cash flow lives in one place.",
        ],
      ],
    },
    footer: {
      desc: "Management software for racquet clubs: bookings, payments, members, tournaments and rankings. A MatchPro product.",
      producto: "Product",
      productoLinks: [
        ["#producto", "Operations"],
        ["#ecosistema", "Ecosystem"],
        ["#clientes", "Clients"],
        ["#faq", "FAQ"],
      ],
      ecosistema: "Ecosystem",
      matchproJugadores: "MatchPro — for players",
      contacto: "Contact",
      agendar: "Book a demo",
      copyright: "Built in Chile",
      transbank: "Payments certified by Transbank",
    },
  },
};
